version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../dockerfiles/frontend.Dockerfile
    environment:
      NODE_ENV: production
    restart: always
    expose:
      - 80
    volumes:
      - ./frontend:/app
    command: npm run serve

  backend:
    build:
      context: ./backend
      dockerfile: ../dockerfiles/backend.Dockerfile
    environment:
      NODE_ENV: production
    restart: always
    expose:
      - 3000
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    command: node src/index.js

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo:/data/db