version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./frontend/src:/usr/app/src
    command: npm run dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/app
    depends_on:
      - mongo
    command: node index.js

  mongo:
    image: mongo:latest
    expose:
      - 27017
    restart: always
    volumes:
      - ./mongo:/data/db